// Copies the compiled ABIs from contracts/out into src/lib/chain/abi as `as const` TypeScript modules so
// viem can infer function and event types. Run after `forge build`:  node scripts/export-abis.mjs
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "lib", "chain", "abi");
mkdirSync(outDir, { recursive: true });

for (const name of ["DarefulLedger", "DarefulDares"]) {
  const artifact = JSON.parse(readFileSync(join(root, "contracts", "out", `${name}.sol`, `${name}.json`), "utf8"));
  const exportName = name[0].toLowerCase() + name.slice(1) + "Abi";
  const body =
    `// Generated by scripts/export-abis.mjs from contracts/out/${name}.sol/${name}.json. Do not edit.\n` +
    `export const ${exportName} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(join(outDir, `${name}.ts`), body);
  console.log(`wrote src/lib/chain/abi/${name}.ts (${artifact.abi.length} entries)`);
}
